[package]
name = "waybar-autohide"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.143"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
